### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jairforero** [deluan/lookup#3] opened 2020-06-29 23:27 UTC
Hi, not work library . have a main package?

Thanks!

**Comment by deluan** [comment] 2020-06-29 23:45
Hey, thanks for trying my library. What is the error you are seeing? Please give more details.

For working examples, please take a look at the files https://github.com/deluan/lookup/blob/master/examples_lookup_test.go and https://github.com/deluan/lookup/blob/master/examples_ocr_test.go

**Comment by jairforero** [comment] 2020-06-30 01:36
Thanks!, this file say "no have a main"

**Comment by deluan** [comment] 2020-06-30 01:42
Yes, these are [example files](https://golang.org/pkg/testing/#hdr-Examples). You have to change the package to main and rename the `Example_ocr` to `main`

**Comment by jairforero** [comment] 2020-06-30 02:05
I rename file say this " main.go:8:2: found packages lookup (doc.go) and lookup_test"

Thanks!"

**Comment by deluan** [comment] 2020-06-30 02:09
This should work:

```golang
package main

import (
	"fmt"
	"image"
	"os"

	"github.com/deluan/lookup"
)

// Helper function to load an image from the filesystem
func loadImage(imgPath string) image.Image {
	imageFile, _ := os.Open(imgPath)
	defer imageFile.Close()
	img, _, _ := image.Decode(imageFile)
	return img
}

func main() {
	// Load full image
	img := loadImage("testdata/cyclopst1.png")

	// Create a lookup for that image
	l := lookup.NewLookup(img)

	// Load a template to search inside the image
	template := loadImage("testdata/cyclopst3.png")

	// Find all occurrences of the template in the image
	pp, _ := l.FindAll(template, 0.9)

	// Print the results
	if len(pp) > 0 {
		fmt.Printf("Found %d matches:\n", len(pp))
		for _, p := range pp {
			fmt.Printf("- (%d, %d) with %f accuracy\n", p.X, p.Y, p.G)
		}
	} else {
		println("No matches found")
	}

	// Output:
	// Found 1 matches:
	// - (21, 7) with 0.997942 accuracy
}
```

**Comment by jairforero** [comment] 2020-06-30 06:29
Thank ! but same error
main.go:8:2: found packages lookup (doc.go) and main (main.go)

**Comment by deluan** [comment] 2020-06-30 13:02
You may have misunderstood what this project is. This is a _library_ to add simple OCR capabilities to programs written in Go. It **is not** a standalone application. The errors you are getting seems to be caused by you trying to "run" this project, something that it was not meant to do. It does not provide a main, you should write your own, the files above are just examples of usage, not full featured applications.

Maybe you are looking for a self-contained, ready-to-use application, like [Sikuli](http://sikulix.com/)?

**Comment by jairforero** [comment] 2020-06-30 13:41
Friend I have this with go I you see the error send is of Go compiler after of run Go Run main.go, if I see this file have name of package but no code, Very thanks!

**Comment by deluan** [comment] 2020-06-30 13:51
I know the error is from the Go compiler, and that's caused by the fact that you are probably cloning this repo and creating a main file in the checked out code. And that's not how you use a Go library. You should have your own Go project and use `go get github.com/deluan/lookup` to add this library to your project. Then, in your project, you call the library in the same way you see in the examples above. 

Hope this clarifies things a bit.

**Comment by jairforero** [comment] 2020-07-01 06:02
Thanks, nor other error
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x4a687e]

goroutine 1 [running]:
github.com/deluan/lookup.ensureGrayScale(0x0, 0x0, 0x4c1c00, 0xc000006080)
        C:/Users/JairForero/go/src/github.com/deluan/lookup/helpers.go:14 +0x7e
github.com/deluan/lookup.NewLookup(0x0, 0x0, 0x0)
        C:/Users/JairForero/go/src/github.com/deluan/lookup/lookup.go:15 +0x40
main.main()
        C:/Users/JairForero/go/src/github.com/jairforero/bot/test.go:24 +0x67
exit status 2

**Comment by deluan** [comment] 2020-07-01 13:52
Can I see the code where you are calling the `lookup.NewLookup` function? Can you send me the images you are using?

**Comment by jairforero** [comment] 2020-07-03 22:55
Hi Call ensureGrayScale line 14 in file lookup.go in line 15
I use images of folder testdata/cyclops1.png exist in folder deluan/lookup and copy in my project folder
Thanks

**Comment by deluan** [comment] 2020-09-10 13:15
Sorry, I cannot reproduce your issue in my local environment. Seems to be an issue with your GoLang installation. I'll close this now, but feel free to reopen attaching a sample project that reproduces the issue, and I can to take a look.

**Closed by deluan** 2020-09-10 13:15 UTC
